version: "3"


services:
  # The service to configure and initialize a new workflow
  copier: 
    build:
      context: .
      dockerfile: Dockerfile
      target: copier
    image: copier_rnaseq:latest
    command: ["copy","/mnt/workflow","/mnt/workflows/test_analysis"]
    volumes:
      # - ./:/mnt/workflow
      # New analyses can be saved here
      # Testing:
      - ./workflows:/mnt/workflows
      # Production:
      #- /home/ngsinternal/workflows:/mnt/workflows
      