version: "3"

volumes:
  conda-envs:
    external: true
  # homo_sapiens:
  #   external: true
  bigtmp:
    external: true

services:
  workflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: rnaseq:latest
    command: ["snakemake","--use-conda","-c3","-p"]
    volumes:
      - conda-envs:/conda-envs
      - "./.test/config:/mnt/workflow/config"
      - "/media/user/ref_genomes/homo_sapiens/resources:/mnt/workflow/resources/homo_sapiens"
      # - "./.test/out/results:/mnt/workflow/results"
      # - "./.test/resources/reads:/mnt/workflow/resources/reads"
      - "./resources:/mnt/workflow/resources"
      - "./results:/mnt/workflow/results"
      - "./workflow:/mnt/workflow/workflow"
      - "./logs:/mnt/workflow/logs"
      # - homo_sapiens:/mnt/workflow/resources/homo_sapiens
      - bigtmp:/bigtmp
